EduOne/EduOne/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

EduOne/main/urls.py
# """EduOne URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/2.1/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views, forms
from .forms import *


urlpatterns = [
 ###==================================Common===========================================================    

     ##Start of paths for login & logout
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
     #End of paths for login & logout

    ##(Common) Start of main path for the website
    path('home/', views.home, name='main-home'),
     #End of main path for the website

    ##(Common) Start of common paths for scheduling functions 
    path('schedule/', views.schedule, name='schedule-home' ),
    path('schedule/<int:month>/<int:year>', views.schedule, name='schedule-home' ),
    # End of common paths for scheduling functions (parents & teachers)

###==================================End of Common=========================================================== 

###==================================Teachers Functions=========================================================== 
    ##(Teachers) Start of scheduling functions for teachers
    path('schedule/manage/', views.schedule_manage, name='schedule-manage'),
    path('schedule/manage=<str:current>/', views.schedule_manage, name='schedule-manage'),
    path('schedule/<str:status>/<int:pk>', views.schedule_pending_manage, name='schedule-pending-manage'),
    path('schedule/add/', views.schedule_add, name='schedule-add'),
    path('schedule/add=<str:current>/', views.schedule_add, name='schedule-add'),
    path('schedule/edit=<str:stype>/<int:pk>/', views.schedule_edit, name='schedule-edit'), 
    #End of paths for scheduling functions

    #(Teachers) Start of django class form for scheduling functions
    path('announcement/<int:pk>/', AnnouncementDetailView.as_view(), name = 'announcement-detail'),
    path('announcement/<int:pk>/delete/', AnnouncementDeleteView.as_view(), name = 'announcement-delete'),
    path('event/<int:pk>/', EventDetailView.as_view(), name = 'event-detail'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name = 'event-delete'),
    path('appointment/<int:pk>/', AppointmentDetailView.as_view(), name = 'appointment-detail'),
    path('appointment/rejected/<int:pk>', StaffAppointmentUpdateView.as_view(), name = 'appointment-update-staff'),
    #End of paths for scheduling functions

    #(Teachers) Start of paths for student settings functions
    path('attendance/', views.attendance, name='attendance-home'),
    path('attendance/<str:status>/<str:id>', views.attendance_edit, name='attendance-edit' ),
    path('grades/', views.grades, name='grades-home' ), #Student Settings -> Manage Grades
    path('grades/<str:id>', views.grades, name='grades-home'), #Student Settings -> Manage Grades -> Manage Grades
    path('grades/<str:id>/<int:report_card_page_id>', views.grades_manage, name='grades-manage'), #Student Settings -> Manage Grades -> Manage Grades -> Click examination name
    path('grades/<str:id>/<int:report_card_page_id>/add/', views.grades_add, name='grades-add' ),
    path('grades/<str:id>/<int:report_card_page_id>/delete/<int:pk>', Grades_Delete_Form.as_view(template_name = "student_settings/grades_delete.html"), name='grades-delete' ), 
    path('grades/<str:id>/<int:report_card_page_id>/edit/<int:pk>', grades_edit.as_view(template_name = "student_settings/grades_edit.html"), name='grades-edit'), #Student Settings -> Manage Grades -> Manage Grades -> Click examination name -> Click edit
    path('grades/<str:id>/add/<int:count>', views.report_card_page_add, name='report-card-page-add' ), #not finished
    path('performance/', views.performance, name='performance-home'),
    path('performance/<int:class_id>', views.performance, name='performance-home'),
    path('performance/<int:class_id>/<str:subject>/<str:id>', views.comment_add, name='performance-add'),
    #End of paths for student settings functions
###===========================End of Teachers Functions=========================================================== 

###==================================Parents Functions=========================================================== 
    #Start of paths for parent's scheduling functions
    path('schedule/appointment-add/', views.appointment_add, name='appointment-add'), 
    path('schedule/appointment-manage/', views.appointment_manage, name='appointment-manage'),
    path('schedule/appointment-manage=<str:current>/', views.appointment_manage, name='appointment-manage'),
    #End of paths for parent's scheduling functions
    
    #Start of paths for appointment's manage functions
    path('appointment-edit/<int:pk>/', AppointmentUpdate.as_view(template_name = "appointment/appointment_update.html"), name = 'appointment-update'),
    path('appointment-pending/<int:pk>/delete/', AppointmentPendingDeleteView.as_view(template_name = "appointment/appointment_pending_delete.html"), name = 'appointment-pending-delete'),
    path('appointment-approved/<int:pk>/delete/', AppointmentApprovedDeleteView.as_view(template_name = "appointment/appointment_approved_delete.html"), name = 'appointment-approved-delete'),
    #End of paths for appointment's manage functions\

    #Start of paths for child's profile functions
    path('childslist/', views.childlist, name='childs'),
    path('childslist/<str:id>/profile/', views.childprofile, name='child-profile'),
    path('childslist/<str:id>/profile/reportcard/<int:rcid>/', views.childreportcardpage, name='report-card-page'),
    path('childslist/<str:id>/profile/reportcard/<int:pk>/acknowledge', ReportCardPageAcknowledgementView.as_view(template_name = "child/child-report-card-acknowledge.html"), name='report-card-page-acknowledge'),
    path('childslist/<str:id>/profile/attendance/', views.childattendance, name='child-attendance'),
    path('childslist/<str:id>/profile/comments/', views.childcomments, name='child-comments'),
    #End of paths for child's profile functions
###===========================End of Parents Functions===========================================================     

###=========================== For Trials======================================================

]

EduOne/main/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now

# Create your models here.
class User(AbstractUser):
    is_staff = models.BooleanField('Staff status', default=False)
    is_parent = models.BooleanField('Parent status', default=False)


class ParentProfile(models.Model):
    RELATION_CHOICES = (
        ('Father', 'Father'),
        ('Mother', 'Mother'),
    )

    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE,
    )
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    contact_number = models.CharField(max_length=20)
    relation = models.CharField(max_length=6, choices=RELATION_CHOICES)

    def __str__(self):
        return "{} {}".format(self.lastname, self.firstname)


class Class(models.Model):
    className = models.CharField(max_length=10)

    def __str__(self):
        return "{}".format(self.className)


class SubjectClass(models.Model):
    classOf = models.ForeignKey(
        'Class',
        on_delete=models.CASCADE,
    )
    student = models.ManyToManyField(
        'Student',
        through='StudentToSubjectClass',
        through_fields=('subjectClass', 'student'),
    )
    teacher = models.ForeignKey(
        'StaffProfile',
        null=True,
        on_delete=models.SET_NULL,
    )
    subject = models.CharField(max_length=20)

    def __str__(self):
        return "Class: {}, Teacher: {}, Subject: {}".format(self.classOf, self.teacher, self.subject)


class StaffProfile(models.Model):

    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE
    )
    form_class = models.ForeignKey(
        'Class',
        null=True,
        on_delete=models.SET_NULL,
    )
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    contact_number = models.CharField(max_length=20)

    def __str__(self):
        return "{} {}".format(self.lastname, self.firstname)


class Student(models.Model):
    child_of = models.ForeignKey(
        'ParentProfile', 
        null=True, 
        on_delete=models.SET_NULL,
    )
    form_class = models.ForeignKey(
        'Class',
        null=True,
        on_delete=models.SET_NULL,
    )
    
    nric = models.CharField(max_length=9, primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    home_address = models.CharField(max_length=100)
    emergency_contact = models.CharField(max_length=20)

    def __str__(self):
        return "Student: {} {}".format(self.last_name, self.first_name)


class StudentToSubjectClass(models.Model):
    subjectClass = models.ForeignKey(
        'SubjectClass', 
        on_delete=models.CASCADE,
    )
    student = models.ForeignKey(
        'Student', 
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "{} {}".format(self.subjectClass, self.student)

    class Meta:
        # all db options go here; sort, order by, index etc..
        unique_together = ("subjectClass", "student")


class ReportCard(models.Model):
    student = models.OneToOneField(
        'Student', 
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "{}'s RCard".format(self.student)


class ReportCardPage(models.Model):
    reportCard = models.ForeignKey(
        'ReportCard',
        on_delete=models.CASCADE,
    )
    examination_type = models.CharField(max_length=20)
    exam_date = models.DateField()
    description = models.CharField(max_length=200)
    acknowledgement = models.BooleanField(default=False)

    def __str__(self):
        return "{} | {} | {}".format(self.examination_type, self.exam_date, self.reportCard)


class SubjectGrade(models.Model):
    reportCardPage = models.ForeignKey(
        'ReportCardPage', 
        on_delete=models.CASCADE,
    )
    subjectName = models.CharField(max_length=50)
    marks = models.DecimalField(max_digits=3, decimal_places=1)

    def __str__(self):
        return "{} {}".format(self.reportCardPage, self.subjectName)


class Comment(models.Model):
    student = models.ForeignKey(
        'Student', 
        on_delete=models.CASCADE,
    )
    commentBy = models.CharField(max_length=50)
    commentDate = models.DateField(default=now())
    commentTime = models.TimeField(default=now())
    comment = models.CharField(max_length=200)

    def __str__(self):
        return "Comment by: {} for {}".format(self.commentBy, self.student)


class Attendance(models.Model):
    student = models.ForeignKey(
        'Student',
        on_delete=models.CASCADE,
    )
    date = models.DateField(default=now())

    def __str__(self):
        return "{} | {}".format(self.date, self.student)
    
    class Meta:
        unique_together = ("student", "date")


class EventPlanner(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,    
    )

    def __str__(self):
        return "{}'s Planner".format(self.user)


class Event(models.Model):
    eventPlanner = models.ForeignKey(
        'EventPlanner',
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=50)
    dateFrom = models.DateField()
    dateTo = models.DateField()
    timeFrom = models.TimeField()
    timeTo = models.TimeField()

    def __str__(self):
        return "{}, Date From: {}, Date To: {}, From: {}, To: {}".format(self.eventPlanner, self.dateFrom, self.dateTo, self.timeFrom, self.timeTo)

APPOINTMENT_STATUS = (
    ('pending', 'Pending'),
    ('approved', 'Approved'),
    ('rejected', 'Rejected')
    )

class Appointment(models.Model):
    eventPlanner = models.ForeignKey(
        'EventPlanner',
        on_delete=models.CASCADE,
    )
    parent = models.ForeignKey(
        'ParentProfile',
        on_delete=models.CASCADE,
    )
    apptTitle = models.CharField(max_length=30)
    apptDescription = models.CharField(max_length=200)
    apptDate = models.DateField()
    apptLocation = models.CharField(max_length=50)
    apptTimeFrom = models.TimeField()
    apptTimeTo = models.TimeField()
    apptStatus = models.CharField(max_length=8, choices=APPOINTMENT_STATUS, default = 'pending')
    apptRejectionReason = models.CharField(max_length=200, default = '-')

    def __str__(self):
        return "Appt by: {} | Status: {}".format(self.parent, self.apptStatus)


class Announcement(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=500)
    dateCreated = models.DateField()

    def __str__(self):
        return "User: {}, title: {}".format(self.user, self.title)

EduOne/main/templates/student_settings/attendance.html
{% include "common/header.html" %}

{% block content %}
<!DOCTYPE html>
<style>
	th {
		background-color: #FA9483;
		text-align: center;
	}

	td {text-align: center;}

	.container-fluid a {
		color: #000000;
		font-weight: bold;
	}
</style>

<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12 text-center">
				<h2 style="padding:1%;">Class {{information.teacher_info.className}} Student Attendance</h2>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 text-left">
				Date: {{information.today}}
			</div>

			<div class="col-md-6 text-right">
				Attendance: {{information.attendanceCount}}/{{information.students.count}}
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 text-left">
				Taken by: {{information.teacher_info}}
			</div>

			<div class="col-md-6 text-right">
				<a href="{% url 'attendance-edit' id=user.id status='all' %}">Select all</a>
			</div>
		</div>
	
		<table class="table table-hover" style="margin-top: 2%;">
			<tr>
				<th>S/N</th>
				<th>Student Name</th>
				<th>Present?</th>
			</tr>
			{% for student in information.students %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{student.last_name}}  {{student.first_name}}</td>
				<td>
				{% if student in information.present %}
					<a href="{% url 'attendance-edit' id=student.nric status='Y' %}">Y</a></td>
				{% else %}
					<a href="{% url 'attendance-edit' id=student.nric status='N' %}">N</a></td>		
				{% endif %}	
			</tr>
			{% endfor %}
		</table>
	</div>
</body>
</html>
{% endblock %}

EduOne/main/templates/student_settings/grades.html
{% include "common/header.html" %}
{% block content %}
<!DOCTYPE html>
<head>

</head>

<style>
	h2 {
		text-align: center;
		/*top right bottom left*/
		padding: 1% 0 0 0;
	}

	#class {
		justify-content: center;
	}

	table {
		text-align: center;
	}

	#studentlist {
		justify-content: center;
	}

	p {
		position: static;
		padding-left: 1.5%;
		padding-bottom: 2%;
		margin-bottom: -1%;
		margin-top: 3%;
	}

	table a {
		color: #000000;
	}

	table a:hover {
		text-decoration: none;
		color: #6893C3;
		font-weight: bold;

	}

	#manageGradesTable {
		position: relative;
		margin-top: 2%;
	}

	th {
		background-color: #FA9483;
	}


</style>

<body>
	<div class="maincontainer">
	<div class="container-fluid">
		{% if information.view == 'class'%}
		<div class="row" id="class">
			<h2>Class {{information.teacher_info.form_class.className}}</h2>
		</div>

		<div class="row" id="studentlist" style="margin-top: 0.5%;">
			<h5 style="font-size: 15px;">Student List</h5>
		</div>
		
		<div class="row" id="teacher">
			<p>Taken by: {{information.teacher_info}}</p>
		</div>

		<table class="table table-hover table-bordered">
			<tr>
				<th style="width: 10%;">S/N</th>
				<th style="width: 45%;">Student Name</th>
				<th>Tools</th>
			</tr>

			{% for student in information.students %}
			<tr>
				<td class="align-middle">{{forloop.counter}}</td>
				<td class="align-middle">{{student.last_name}}  {{student.first_name}}</td>
				<td><a href="{% url 'report-card-page-add' id=student.nric count=1 %}">Add Grades</a><br>
				<a href="{% url 'grades-home' id=student.nric%}">Manage Grades</a></td>
			</tr>
			{% endfor %}
		</table>

	<!--this table will show up after clicking on manage grades-->
	{% elif information.view == 'student' %}
		<h2>Manage Grades</h2>
		<table class="table table-bordered table-hover" id="manageGradesTable">
		<tr>
			<th style="width: 70%;">Title</th>
			<th>Year</th>
		</tr>
		{% for page in information.pages %}
			<tr>
				<td><a href="{% url 'grades-manage' id=information.nric report_card_page_id=page.id %}">{{page.examination_type}}</a></td>
				<td>{{page.exam_date.year}}</td>
			</tr>
		
		{% endfor %}
		</table>
	{% endif %}	
		
</body>
</html>
{% endblock %}

EduOne/main/templates/student_settings/grades_add.html
{% load widget_tweaks %}
{% block content %}

<!DOCTYPE html>
<style>
    #cross {
        position: absolute;
        left: 96%;
        top: 1%;
    }

    .btn-outline-success {
        margin-top: 3%;
        margin-bottom: 3%;
        width: 50%;

    }
</style>

<body>
    <div class="container-fluid">
        <div class="modal-header" style="border-bottom: none;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" id="cross">&times;</span>
                </button>
        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                <h4>Add Subject Grade</h4>
            </div>
        </div>

        <form method="POST" autocomplete="off">

            {% csrf_token %}

            {{ form.non_field_errors }}
			{{ form.source.errors }}
			{{ form.source }}
        
            <div class="form group">
                <div class="row" style="padding:15px;">
                    {{ form.title.label_tag }}
                    {{ form.title|add_class:'form-control' }}
                </div>
            </div>
            
            <div class="form group">
                <div class="row" style="padding:15px;">
                    {{ form.subjectName.label_tag }}
                    {{ form.subjectName|add_class:'form-control' }}
                </div>
            </div>
            
            <div class="form group">
                <div class="row" style="padding:15px;">
                    {{ form.marks.label_tag }}
                    {{ form.marks|add_class:'form-control' }}
                </div>
            </div>

			<div class="row">
                <div class="col-md-12 text-center">
                    <input type='submit' value = 'Save' class="btn btn-outline-success">
                </div> 
            </div>
        </form>
    </div>
</body>
</html>
{% endblock %}

EduOne/main/templates/student_settings/grades_delete.html
{% block content %}
<!DOCTYPE html>
<style>
	.modal-header {
		border-bottom: none;
	}

	#cross {
		position: absolute;
        left: 96%;
        top: 1%;
	}

	#icon {
		font-size: 68px;
		color: #E63946;
		margin-bottom: 2%;
	}

	.btn-outline-dark, .btn-outline-success {
		width: 60%;
	}
</style>

<body>
	<div class="container-fluid">
		<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true" id="cross">&times;</span>
				</button>
		</div>

		<div class="row">
				<div class="col-md-12 text-center">
					<i class="fas fa-exclamation" id="icon"></i>
				</div>
		</div>


	<!--Start of Form-->
		<form method="POST">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-12 text-center">
					<h4>Are you sure you want to delete grades</h4>
				</div>
			</div>

			<div class="row" style="margin-bottom: 3%;">
					<div class="col-md-6 text-center">
						<a href ="{% url 'grades-home' %}" class="btn btn-outline-dark" role="button"> No </a></button>
					</div>

					<div class="col-md-6 text-center">
						<button type ="submit" class="btn btn-outline-success"> Yes </button>
					</div>
			</div>
		</form>
	</div>
	<!--End of Form-->
	</div>
</body>
</html>	
{% endblock %}

EduOne/main/templates/student_settings/grades_edit.html
{% block content %}
{% load widget_tweaks %}
<!DOCTYPE html>
<style>
    .modal-header {
        border-bottom: none;
    }

    #cross {
        position: absolute;
        left: 96%;
        top: 1%;
    }

    h2 {
        margin-bottom: 2%;
    }

    #id_marks {
        border-radius: 3px;
        border:1px solid black;
        width: 55%;
        margin-top: 3%;
        margin-bottom: 3%;
    }

    label {
        display: none;
    }

    .btn-outline-success {
        width: 30%;
        margin-bottom: 3%;
    }


</style>
<body>
    <div class="container-fluid">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true" id="cross">&times;</span>
            </button>
        </div>

        <div class="row">
            <div class="col-md-12">
                <h2>Edit Marks</h2>
            </div>
        </div>

        <form method="POST" class="text-center">
            {% csrf_token %}
            {{ form.as_p }}
            <input type='submit' value = 'Save' class="btn btn-outline-success">
        </form>
    </div>
</body>


</html>
{% endblock %}

EduOne/main/templates/student_settings/grades_manage.html
{% include "common/header.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<head>
		<script src="{% static 'common/js/jquery.bootstrap.modal.forms.js' %}"></script>
		<script src="{% static 'common/js/bootstrap.bundle.min.js' %}"></script>
		
		
</head>

<style>
	h2 {
		text-align: center;
		padding: 1%;
	}

	table {
		text-align: center;
	}

	#backButton {
		border: 1px solid #C5C3C6;
		border-width: 1px 1px 1px 0;
		border-radius: 0 5px 5px 0;
		display: inline-block;
		height: 75%;
		margin-left: 5%;
		margin-bottom: 4%;
		padding: 0 2% 0 1%;
		position: relative;
		text-decoration: none;
		background-color: #B4B2B4;
		color: #ffffff;
		font-weight: bold;
	}

	#backButton::before {
		border: solid #B4B2B4;
		background: linear-gradient(-45deg, #B4B2B4 0%, #B4B2B4 100%);
		border-width: 0 0 1px 1px;
		border-radius: 2px 0 2px 2px;
		content: '';
		display: block;
		height: 24px;
		left: -7%;
		position: absolute;
		top: 3px;
		-moz-transform: rotate(45deg);
		-webkit-transform: rotate(45deg);
		-o-transform: rotate(45deg);
		transform: rotate(45deg);
		width: 21px;
	}

	#backButton span {
		color: #fff;
		font-weight: bold;
		position: relative;
	}

	#backButton span:hover {
		color: #000000;
	}


	table a {
		color: #000000;
		padding: 10%;
	}
	table a:hover {
		text-decoration: none; 
	}

	th {
		background-color: #FA9483;
	}

	#addGradeButton {
		border: 1px solid #B4B2B4;
		float: right;
		border-radius: 2px;
		background-color: #B4B2B4;
		color: #ffffff;
		font-weight: bold;	
		padding: 1%;
		margin-bottom: 3%;
	}

	#addGradeButton:hover{
		text-decoration: none;
		color: #000000;
	}

	.fa-pen:hover {
		color: #6893C3;
	}
	
	.editGrades, .deleteGrades {
		border: none;
		background: none;
	}

	
</style>

<body>
	<div class="container-fluid">
	{% if information.grades|length == 0 %}
		<p>No records of grades found!</p>
		<p><a href="{% url 'grades-add' id=information.nric report_card_page_id=information.report_card.id %}">Add subject grade</a></p>
	{% else %}
		<div class="row">
			<div class="col-md-12">
				<h2>Grades for {{information.report_card.examination_type}}</h2>
			</div>
		</div>
		
		<div class="row" style="margin-top: 3%;"> 
			<div class="col-md-3">
				<a href="{% url 'grades-home' id=information.nric %}" id ="backButton"><span>Return to previous</span></a>
			</div>

			<div class="col-md-6"></div>
			<div class="col-md-3">
				<button id="addGradeButton" btn data-id="{% url 'grades-add' id=information.nric report_card_page_id=information.report_card.id %}">Add subject grade</button>
			</div>
		</div>


		<table class="table table-hover table-bordered">
			<tr>
				<th width="10%;">S/N</th>
				<th>Subject</th>
				<th style="width: 20%;">Grade Achieved</th>
				<th>Marks</th>
				<th style="width: 10%;">Tools</th>
			</tr>
			{% for grade in information.grades %}
			<tr>
				<td class="align-middle">{{forloop.counter}}</td>
				<td class="align-middle">{{grade.subjectName}}</td>
				{% if grade.marks >= 75 %}
					<td class="align-middle">A
				{% elif grade.marks >= 65%}
					<td class="align-middle">B
				{% elif grade.marks >= 50 %}	
					<td class="align-middle">C
				{% else %}
					<td class="align-middle">D
				{% endif %}			
				</td>
				<td class="align-middle">{{grade.marks}}</td>
				<td><button class= "editGrades" btn data-id="{% url 'grades-edit' id=information.nric report_card_page_id=information.report_card.id pk=grade.id %}" data-toggle="tooltip" title="Edit marks" data-placement="bottom"><i class="fas fa-pen"></i></button>
				<button class="deleteGrades" btn data-id="{% url 'grades-delete' id=information.nric report_card_page_id=information.report_card.id pk=grade.id %}" data-toggle="tooltip" title="Delete grades" data-placement="bottom"><i class="fas fa-trash-alt"></i></button></td>
			</tr>
			{% endfor %}
		</table>
		
		<!--popup form for edit marks-->
		<div class="modal fade" tabindex="-1" role="dialog" id="modal">
				<div class="modal-dialog" role="document">
					<div class="modal-content"></div>
				</div>
		</div>

	{% endif %}	
	</div>
</body>
<script>
	$(function () {
 		 $('[data-toggle="tooltip"]').tooltip()
	})

	$(".editGrades").each(function () {
		$(this).modalForm({formURL: $(this).data('id')});
	});

	$(".deleteGrades").each(function () {
		$(this).modalForm({formURL: $(this).data('id')});
	});

	$("#addGradeButton").each(function () {
		$(this).modalForm({formURL: $(this).data('id')});
	});




</script>
</html>
{% endblock %}

EduOne/main/templates/student_settings/performance_add.html
{% block content %}
{% load widget_tweaks %}
<!DOCTYPE html>
<head>

</head>

<style>
	span {
		position: absolute;
		left: 96%;
		top: 1%;
	}


</style>

<body>
	<div class="container-fluid">
		<div class="modal-header" style="border-bottom: none;">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
		</div>

		<div class="row">
			<div class="col-md-12 text-center">
				<h2>Comment Performance</h2>
			</div>
		</div>

		<div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-11">
					<!--Start of Display Errors-->
					{% if messages %}
						{% for message in messages %}
							<!--<div class = "alert alert-{{message}}"></div>-->
							{{message}}
						{% endfor %}
					{% endif %}		
				<!--End of Display Errors-->
				</div>
			</div>
	


		<!--Start of Form-->
			<form method="POST">
				{% csrf_token %}
				<div class="row">
					<div class="col-md-12 text-center">
						<p>Commenting for {{information.student.last_name}} {{information.student.first_name}}</p>
					</div>
				</div>

				<div class="form group">
						<div class="row" style="padding:15px;">
							{{ form.comment.label_tag }}
							{{ form.comment|add_class:'form-control' }}
						</div>
					</div>

				<div class="row" style="padding: 1%;">
					<div class="col-md-6 text-center">
						<a href ="{% url 'performance-home' %}" class="btn btn-outline-dark" role="button"> Return </a>
					</div>

					<div class="col-md-6 text-center">
							<button type ="submit" class="btn btn-outline-success">Save Comment</button>
					</div>
				</div>
			</form>
		</div>
		<!--End of Form-->
	</div>
</body>
</html>
{% endblock %}